# fly.toml app configuration file generated for frab-app on 2025-08-01T04:41:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frab-app'
primary_region = 'sin'
console_command = '/rails/bin/rails console'

[build]

[[mounts]]
  source = 'public'
  destination = '/home/frab/app/public'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
